# Generated by Django 3.1.7 on 2021-03-17 19:44

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='custom_url',
            field=models.CharField(blank=True, default=catalog.models.generate_custom_url, max_length=8),
        ),
        migrations.AlterField(
            model_name='content',
            name='source_url',
            field=models.URLField(blank=True, help_text='Content source URL'),
        ),
    ]
