# Generated by Django 3.1.7 on 2021-03-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210317_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.FileField(upload_to='content/%Y/%m/%d'),
        ),
    ]
